/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mingthegamer' at '18/11/17 22:09' with Gradle 2.14.1
 *
 * @author mingthegamer, @date 18/11/17 22:09
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
